// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 2);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "US");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"08051886-72e0-48b5-93d8-092122226237\",\"default-theme@mozilla.org\":\"5eaed0bc-4c3e-451d-a1a3-43816a1f91ca\",\"google@search.mozilla.org\":\"2ff74ce6-41b8-4777-83b6-43124acbbd78\",\"amazondotcom@search.mozilla.org\":\"22188798-d10f-46b1-9753-5ffe9b8b12d3\",\"bing@search.mozilla.org\":\"5671601b-566b-48c1-9149-e87692d50cf6\",\"ddg@search.mozilla.org\":\"7f93f2e3-9e0c-4e07-a594-496bd26b9ca2\",\"twitter@search.mozilla.org\":\"eef797b7-4e75-4b33-9621-266f60135193\",\"wikipedia@search.mozilla.org\":\"cb8c0dfb-3c4d-4b52-83b1-18a345fe3e39\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "bd93e1c5-8e0d-4b2d-9eb4-a5989f40acf");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "f338e22a-89ec-40e0-9806-f78d9b0ada4c");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.prompted", 2);
